/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Avocado(props) {
  const { nodes, materials } = useGLTF('/avocado/food_avocado_01_4k.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.food_avocado_01.geometry} material={materials.food_avocado_01} />
    </group>
  )
}

useGLTF.preload('/avocado/food_avocado_01_4k.gltf')
