/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Calendine(props) {
  const { nodes, materials } = useGLTF('/greenTexture/celandine_01_4k.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.celandine_01_e_LOD0.geometry} material={materials.celandine_01} />
    </group>
  )
}

useGLTF.preload('/greenTexture/celandine_01_4k.gltf')
